// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_connect_widget.cpp"
#include "UVLADIE3JM/moc_port_handler.cpp"
#include "UVLADIE3JM/moc_wg_light.cpp"
#include "UVLADIE3JM/moc_wg_sound.cpp"
#include "UVLADIE3JM/moc_wg_water.cpp"
#include "UVLADIE3JM/moc_widget.cpp"
